command:
  - uvicorn
  - backend.main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: VS_ENDPOINT_NAME
    value: "advance_rag_vs_endpoint"

  - name: VS_INDEX_NAME
    value: "morgancatalog.doc_finder.doc_summaries_index"

  - name: CATALOG
    value: "morgancatalog"

  - name: SCHEMA
    value: "doc_finder"

  - name: VOLUME
    value: "raw_docs"

  - name: FOUNDATION_MODEL
    value: "databricks-gemini-2-5-flash"

  - name: CLASSIFIER_MODEL
    value: "databricks-claude-haiku-4-5"

  - name: MLFLOW_EXPERIMENT
    value: "/Shared/doc-finder"

  - name: DATABRICKS_APP_NAME
    value: "doc-finder"

  - name: MLFLOW_APP_NAME
    value: "doc-finder"
